//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aim.Portal.ServicesProvider.GwUSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GwUSService.UserStateServiceSoap")]
    public interface UserStateServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userInfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserState", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.CreateUserStateResponse CreateUserState(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userInfo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserStateEx", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExResponse CreateUserStateEx(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 workNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserStateByWorkNo", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoResponse CreateUserStateByWorkNo(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserState", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.CheckUserStateResponse CheckUserState(Aim.Portal.ServicesProvider.GwUSService.CheckUserStateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogoutUserState", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateResponse LogoutUserState(Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogoutUserStateEx", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExResponse LogoutUserStateEx(Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPreOut", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.SetPreOutResponse SetPreOut(Aim.Portal.ServicesProvider.GwUSService.SetPreOutRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPreOutEx", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.SetPreOutExResponse SetPreOutEx(Aim.Portal.ServicesProvider.GwUSService.SetPreOutExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RefreshUserState", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateResponse RefreshUserState(Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.GetUserInfoResponse GetUserInfo(Aim.Portal.ServicesProvider.GwUSService.GetUserInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserInfo", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoResponse UpdateUserInfo(Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserData", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.GetUserDataResponse GetUserData(Aim.Portal.ServicesProvider.GwUSService.GetUserDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserData", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataResponse UpdateUserData(Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserProp", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.GetUserPropResponse GetUserProp(Aim.Portal.ServicesProvider.GwUSService.GetUserPropRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserProp", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropResponse UpdateUserProp(Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDataNode", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeResponse GetUserDataNode(Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 passCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserDataNode", ReplyAction="*")]
        Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeResponse SetUserDataNode(Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserState", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.CreateUserStateRequestBody Body;
        
        public CreateUserStateRequest() {
        }
        
        public CreateUserStateRequest(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userName;
        
        public CreateUserStateRequestBody() {
        }
        
        public CreateUserStateRequestBody(string userInfo, string ip, string mac, string userId, string userName) {
            this.userInfo = userInfo;
            this.ip = ip;
            this.mac = mac;
            this.userId = userId;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.CreateUserStateResponseBody Body;
        
        public CreateUserStateResponse() {
        }
        
        public CreateUserStateResponse(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserStateResult;
        
        public CreateUserStateResponseBody() {
        }
        
        public CreateUserStateResponseBody(string CreateUserStateResult) {
            this.CreateUserStateResult = CreateUserStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserStateEx", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExRequestBody Body;
        
        public CreateUserStateExRequest() {
        }
        
        public CreateUserStateExRequest(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string loginMethod;
        
        public CreateUserStateExRequestBody() {
        }
        
        public CreateUserStateExRequestBody(string userInfo, string ip, string mac, string userId, string userName, string loginMethod) {
            this.userInfo = userInfo;
            this.ip = ip;
            this.mac = mac;
            this.userId = userId;
            this.userName = userName;
            this.loginMethod = loginMethod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserStateExResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExResponseBody Body;
        
        public CreateUserStateExResponse() {
        }
        
        public CreateUserStateExResponse(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserStateExResult;
        
        public CreateUserStateExResponseBody() {
        }
        
        public CreateUserStateExResponseBody(string CreateUserStateExResult) {
            this.CreateUserStateExResult = CreateUserStateExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateByWorkNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserStateByWorkNo", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoRequestBody Body;
        
        public CreateUserStateByWorkNoRequest() {
        }
        
        public CreateUserStateByWorkNoRequest(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateByWorkNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string workNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mac;
        
        public CreateUserStateByWorkNoRequestBody() {
        }
        
        public CreateUserStateByWorkNoRequestBody(string workNo, string ip, string mac) {
            this.workNo = workNo;
            this.ip = ip;
            this.mac = mac;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserStateByWorkNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserStateByWorkNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoResponseBody Body;
        
        public CreateUserStateByWorkNoResponse() {
        }
        
        public CreateUserStateByWorkNoResponse(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserStateByWorkNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserStateByWorkNoResult;
        
        public CreateUserStateByWorkNoResponseBody() {
        }
        
        public CreateUserStateByWorkNoResponseBody(string CreateUserStateByWorkNoResult) {
            this.CreateUserStateByWorkNoResult = CreateUserStateByWorkNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserState", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.CheckUserStateRequestBody Body;
        
        public CheckUserStateRequest() {
        }
        
        public CheckUserStateRequest(Aim.Portal.ServicesProvider.GwUSService.CheckUserStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public CheckUserStateRequestBody() {
        }
        
        public CheckUserStateRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.CheckUserStateResponseBody Body;
        
        public CheckUserStateResponse() {
        }
        
        public CheckUserStateResponse(Aim.Portal.ServicesProvider.GwUSService.CheckUserStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserStateResult;
        
        public CheckUserStateResponseBody() {
        }
        
        public CheckUserStateResponseBody(bool CheckUserStateResult) {
            this.CheckUserStateResult = CheckUserStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUserState", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateRequestBody Body;
        
        public LogoutUserStateRequest() {
        }
        
        public LogoutUserStateRequest(Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public LogoutUserStateRequestBody() {
        }
        
        public LogoutUserStateRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUserStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateResponseBody Body;
        
        public LogoutUserStateResponse() {
        }
        
        public LogoutUserStateResponse(Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogoutUserStateResult;
        
        public LogoutUserStateResponseBody() {
        }
        
        public LogoutUserStateResponseBody(bool LogoutUserStateResult) {
            this.LogoutUserStateResult = LogoutUserStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserStateExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUserStateEx", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExRequestBody Body;
        
        public LogoutUserStateExRequest() {
        }
        
        public LogoutUserStateExRequest(Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserStateExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string logoutMethod;
        
        public LogoutUserStateExRequestBody() {
        }
        
        public LogoutUserStateExRequestBody(string passCode, string logoutMethod) {
            this.passCode = passCode;
            this.logoutMethod = logoutMethod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutUserStateExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutUserStateExResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExResponseBody Body;
        
        public LogoutUserStateExResponse() {
        }
        
        public LogoutUserStateExResponse(Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogoutUserStateExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogoutUserStateExResult;
        
        public LogoutUserStateExResponseBody() {
        }
        
        public LogoutUserStateExResponseBody(bool LogoutUserStateExResult) {
            this.LogoutUserStateExResult = LogoutUserStateExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPreOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPreOut", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.SetPreOutRequestBody Body;
        
        public SetPreOutRequest() {
        }
        
        public SetPreOutRequest(Aim.Portal.ServicesProvider.GwUSService.SetPreOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPreOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public SetPreOutRequestBody() {
        }
        
        public SetPreOutRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPreOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPreOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.SetPreOutResponseBody Body;
        
        public SetPreOutResponse() {
        }
        
        public SetPreOutResponse(Aim.Portal.ServicesProvider.GwUSService.SetPreOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetPreOutResponseBody {
        
        public SetPreOutResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPreOutExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPreOutEx", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.SetPreOutExRequestBody Body;
        
        public SetPreOutExRequest() {
        }
        
        public SetPreOutExRequest(Aim.Portal.ServicesProvider.GwUSService.SetPreOutExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPreOutExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string logoutMethod;
        
        public SetPreOutExRequestBody() {
        }
        
        public SetPreOutExRequestBody(string passCode, string logoutMethod) {
            this.passCode = passCode;
            this.logoutMethod = logoutMethod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPreOutExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPreOutExResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.SetPreOutExResponseBody Body;
        
        public SetPreOutExResponse() {
        }
        
        public SetPreOutExResponse(Aim.Portal.ServicesProvider.GwUSService.SetPreOutExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetPreOutExResponseBody {
        
        public SetPreOutExResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshUserStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshUserState", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateRequestBody Body;
        
        public RefreshUserStateRequest() {
        }
        
        public RefreshUserStateRequest(Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RefreshUserStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public RefreshUserStateRequestBody() {
        }
        
        public RefreshUserStateRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RefreshUserStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RefreshUserStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateResponseBody Body;
        
        public RefreshUserStateResponse() {
        }
        
        public RefreshUserStateResponse(Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RefreshUserStateResponseBody {
        
        public RefreshUserStateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.GetUserInfoRequestBody Body;
        
        public GetUserInfoRequest() {
        }
        
        public GetUserInfoRequest(Aim.Portal.ServicesProvider.GwUSService.GetUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public GetUserInfoRequestBody() {
        }
        
        public GetUserInfoRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.GetUserInfoResponseBody Body;
        
        public GetUserInfoResponse() {
        }
        
        public GetUserInfoResponse(Aim.Portal.ServicesProvider.GwUSService.GetUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserInfoResult;
        
        public GetUserInfoResponseBody() {
        }
        
        public GetUserInfoResponseBody(string GetUserInfoResult) {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoRequestBody Body;
        
        public UpdateUserInfoRequest() {
        }
        
        public UpdateUserInfoRequest(Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newUserInfo;
        
        public UpdateUserInfoRequestBody() {
        }
        
        public UpdateUserInfoRequestBody(string passCode, string newUserInfo) {
            this.passCode = passCode;
            this.newUserInfo = newUserInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoResponseBody Body;
        
        public UpdateUserInfoResponse() {
        }
        
        public UpdateUserInfoResponse(Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserInfoResult;
        
        public UpdateUserInfoResponseBody() {
        }
        
        public UpdateUserInfoResponseBody(bool UpdateUserInfoResult) {
            this.UpdateUserInfoResult = UpdateUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserData", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.GetUserDataRequestBody Body;
        
        public GetUserDataRequest() {
        }
        
        public GetUserDataRequest(Aim.Portal.ServicesProvider.GwUSService.GetUserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public GetUserDataRequestBody() {
        }
        
        public GetUserDataRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.GetUserDataResponseBody Body;
        
        public GetUserDataResponse() {
        }
        
        public GetUserDataResponse(Aim.Portal.ServicesProvider.GwUSService.GetUserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserDataResult;
        
        public GetUserDataResponseBody() {
        }
        
        public GetUserDataResponseBody(string GetUserDataResult) {
            this.GetUserDataResult = GetUserDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserData", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataRequestBody Body;
        
        public UpdateUserDataRequest() {
        }
        
        public UpdateUserDataRequest(Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newUserData;
        
        public UpdateUserDataRequestBody() {
        }
        
        public UpdateUserDataRequestBody(string passCode, string newUserData) {
            this.passCode = passCode;
            this.newUserData = newUserData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataResponseBody Body;
        
        public UpdateUserDataResponse() {
        }
        
        public UpdateUserDataResponse(Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserDataResult;
        
        public UpdateUserDataResponseBody() {
        }
        
        public UpdateUserDataResponseBody(bool UpdateUserDataResult) {
            this.UpdateUserDataResult = UpdateUserDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPropRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserProp", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.GetUserPropRequestBody Body;
        
        public GetUserPropRequest() {
        }
        
        public GetUserPropRequest(Aim.Portal.ServicesProvider.GwUSService.GetUserPropRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserPropRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        public GetUserPropRequestBody() {
        }
        
        public GetUserPropRequestBody(string passCode) {
            this.passCode = passCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPropResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPropResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.GetUserPropResponseBody Body;
        
        public GetUserPropResponse() {
        }
        
        public GetUserPropResponse(Aim.Portal.ServicesProvider.GwUSService.GetUserPropResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserPropResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserPropResult;
        
        public GetUserPropResponseBody() {
        }
        
        public GetUserPropResponseBody(string GetUserPropResult) {
            this.GetUserPropResult = GetUserPropResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPropRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserProp", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropRequestBody Body;
        
        public UpdateUserPropRequest() {
        }
        
        public UpdateUserPropRequest(Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserPropRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newUserProp;
        
        public UpdateUserPropRequestBody() {
        }
        
        public UpdateUserPropRequestBody(string passCode, string newUserProp) {
            this.passCode = passCode;
            this.newUserProp = newUserProp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPropResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserPropResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropResponseBody Body;
        
        public UpdateUserPropResponse() {
        }
        
        public UpdateUserPropResponse(Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserPropResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserPropResult;
        
        public UpdateUserPropResponseBody() {
        }
        
        public UpdateUserPropResponseBody(bool UpdateUserPropResult) {
            this.UpdateUserPropResult = UpdateUserPropResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDataNodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDataNode", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeRequestBody Body;
        
        public GetUserDataNodeRequest() {
        }
        
        public GetUserDataNodeRequest(Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDataNodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        public GetUserDataNodeRequestBody() {
        }
        
        public GetUserDataNodeRequestBody(string passCode, string type, string name) {
            this.passCode = passCode;
            this.type = type;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDataNodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDataNodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeResponseBody Body;
        
        public GetUserDataNodeResponse() {
        }
        
        public GetUserDataNodeResponse(Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDataNodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserDataNodeResult;
        
        public GetUserDataNodeResponseBody() {
        }
        
        public GetUserDataNodeResponseBody(string GetUserDataNodeResult) {
            this.GetUserDataNodeResult = GetUserDataNodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserDataNodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserDataNode", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeRequestBody Body;
        
        public SetUserDataNodeRequest() {
        }
        
        public SetUserDataNodeRequest(Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserDataNodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string newDataNode;
        
        public SetUserDataNodeRequestBody() {
        }
        
        public SetUserDataNodeRequestBody(string passCode, string type, string name, string newDataNode) {
            this.passCode = passCode;
            this.type = type;
            this.name = name;
            this.newDataNode = newDataNode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserDataNodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserDataNodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeResponseBody Body;
        
        public SetUserDataNodeResponse() {
        }
        
        public SetUserDataNodeResponse(Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserDataNodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetUserDataNodeResult;
        
        public SetUserDataNodeResponseBody() {
        }
        
        public SetUserDataNodeResponseBody(bool SetUserDataNodeResult) {
            this.SetUserDataNodeResult = SetUserDataNodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserStateServiceSoapChannel : Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserStateServiceSoapClient : System.ServiceModel.ClientBase<Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap>, Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap {
        
        public UserStateServiceSoapClient() {
        }
        
        public UserStateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserStateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserStateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserStateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.CreateUserStateResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.CreateUserState(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateRequest request) {
            return base.Channel.CreateUserState(request);
        }
        
        public string CreateUserState(string userInfo, string ip, string mac, string userId, string userName) {
            Aim.Portal.ServicesProvider.GwUSService.CreateUserStateRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.CreateUserStateRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.CreateUserStateRequestBody();
            inValue.Body.userInfo = userInfo;
            inValue.Body.ip = ip;
            inValue.Body.mac = mac;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            Aim.Portal.ServicesProvider.GwUSService.CreateUserStateResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).CreateUserState(inValue);
            return retVal.Body.CreateUserStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.CreateUserStateEx(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExRequest request) {
            return base.Channel.CreateUserStateEx(request);
        }
        
        public string CreateUserStateEx(string userInfo, string ip, string mac, string userId, string userName, string loginMethod) {
            Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExRequestBody();
            inValue.Body.userInfo = userInfo;
            inValue.Body.ip = ip;
            inValue.Body.mac = mac;
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.loginMethod = loginMethod;
            Aim.Portal.ServicesProvider.GwUSService.CreateUserStateExResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).CreateUserStateEx(inValue);
            return retVal.Body.CreateUserStateExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.CreateUserStateByWorkNo(Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoRequest request) {
            return base.Channel.CreateUserStateByWorkNo(request);
        }
        
        public string CreateUserStateByWorkNo(string workNo, string ip, string mac) {
            Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoRequestBody();
            inValue.Body.workNo = workNo;
            inValue.Body.ip = ip;
            inValue.Body.mac = mac;
            Aim.Portal.ServicesProvider.GwUSService.CreateUserStateByWorkNoResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).CreateUserStateByWorkNo(inValue);
            return retVal.Body.CreateUserStateByWorkNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.CheckUserStateResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.CheckUserState(Aim.Portal.ServicesProvider.GwUSService.CheckUserStateRequest request) {
            return base.Channel.CheckUserState(request);
        }
        
        public bool CheckUserState(string passCode) {
            Aim.Portal.ServicesProvider.GwUSService.CheckUserStateRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.CheckUserStateRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.CheckUserStateRequestBody();
            inValue.Body.passCode = passCode;
            Aim.Portal.ServicesProvider.GwUSService.CheckUserStateResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).CheckUserState(inValue);
            return retVal.Body.CheckUserStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.LogoutUserState(Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateRequest request) {
            return base.Channel.LogoutUserState(request);
        }
        
        public bool LogoutUserState(string passCode) {
            Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateRequestBody();
            inValue.Body.passCode = passCode;
            Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).LogoutUserState(inValue);
            return retVal.Body.LogoutUserStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.LogoutUserStateEx(Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExRequest request) {
            return base.Channel.LogoutUserStateEx(request);
        }
        
        public bool LogoutUserStateEx(string passCode, string logoutMethod) {
            Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.logoutMethod = logoutMethod;
            Aim.Portal.ServicesProvider.GwUSService.LogoutUserStateExResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).LogoutUserStateEx(inValue);
            return retVal.Body.LogoutUserStateExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.SetPreOutResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.SetPreOut(Aim.Portal.ServicesProvider.GwUSService.SetPreOutRequest request) {
            return base.Channel.SetPreOut(request);
        }
        
        public void SetPreOut(string passCode) {
            Aim.Portal.ServicesProvider.GwUSService.SetPreOutRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.SetPreOutRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.SetPreOutRequestBody();
            inValue.Body.passCode = passCode;
            Aim.Portal.ServicesProvider.GwUSService.SetPreOutResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).SetPreOut(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.SetPreOutExResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.SetPreOutEx(Aim.Portal.ServicesProvider.GwUSService.SetPreOutExRequest request) {
            return base.Channel.SetPreOutEx(request);
        }
        
        public void SetPreOutEx(string passCode, string logoutMethod) {
            Aim.Portal.ServicesProvider.GwUSService.SetPreOutExRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.SetPreOutExRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.SetPreOutExRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.logoutMethod = logoutMethod;
            Aim.Portal.ServicesProvider.GwUSService.SetPreOutExResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).SetPreOutEx(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.RefreshUserState(Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateRequest request) {
            return base.Channel.RefreshUserState(request);
        }
        
        public void RefreshUserState(string passCode) {
            Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateRequestBody();
            inValue.Body.passCode = passCode;
            Aim.Portal.ServicesProvider.GwUSService.RefreshUserStateResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).RefreshUserState(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.GetUserInfoResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.GetUserInfo(Aim.Portal.ServicesProvider.GwUSService.GetUserInfoRequest request) {
            return base.Channel.GetUserInfo(request);
        }
        
        public string GetUserInfo(string passCode) {
            Aim.Portal.ServicesProvider.GwUSService.GetUserInfoRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.GetUserInfoRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.GetUserInfoRequestBody();
            inValue.Body.passCode = passCode;
            Aim.Portal.ServicesProvider.GwUSService.GetUserInfoResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).GetUserInfo(inValue);
            return retVal.Body.GetUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.UpdateUserInfo(Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoRequest request) {
            return base.Channel.UpdateUserInfo(request);
        }
        
        public bool UpdateUserInfo(string passCode, string newUserInfo) {
            Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.newUserInfo = newUserInfo;
            Aim.Portal.ServicesProvider.GwUSService.UpdateUserInfoResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).UpdateUserInfo(inValue);
            return retVal.Body.UpdateUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.GetUserDataResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.GetUserData(Aim.Portal.ServicesProvider.GwUSService.GetUserDataRequest request) {
            return base.Channel.GetUserData(request);
        }
        
        public string GetUserData(string passCode) {
            Aim.Portal.ServicesProvider.GwUSService.GetUserDataRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.GetUserDataRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.GetUserDataRequestBody();
            inValue.Body.passCode = passCode;
            Aim.Portal.ServicesProvider.GwUSService.GetUserDataResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).GetUserData(inValue);
            return retVal.Body.GetUserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.UpdateUserData(Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataRequest request) {
            return base.Channel.UpdateUserData(request);
        }
        
        public bool UpdateUserData(string passCode, string newUserData) {
            Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.newUserData = newUserData;
            Aim.Portal.ServicesProvider.GwUSService.UpdateUserDataResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).UpdateUserData(inValue);
            return retVal.Body.UpdateUserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.GetUserPropResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.GetUserProp(Aim.Portal.ServicesProvider.GwUSService.GetUserPropRequest request) {
            return base.Channel.GetUserProp(request);
        }
        
        public string GetUserProp(string passCode) {
            Aim.Portal.ServicesProvider.GwUSService.GetUserPropRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.GetUserPropRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.GetUserPropRequestBody();
            inValue.Body.passCode = passCode;
            Aim.Portal.ServicesProvider.GwUSService.GetUserPropResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).GetUserProp(inValue);
            return retVal.Body.GetUserPropResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.UpdateUserProp(Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropRequest request) {
            return base.Channel.UpdateUserProp(request);
        }
        
        public bool UpdateUserProp(string passCode, string newUserProp) {
            Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.newUserProp = newUserProp;
            Aim.Portal.ServicesProvider.GwUSService.UpdateUserPropResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).UpdateUserProp(inValue);
            return retVal.Body.UpdateUserPropResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.GetUserDataNode(Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeRequest request) {
            return base.Channel.GetUserDataNode(request);
        }
        
        public string GetUserDataNode(string passCode, string type, string name) {
            Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.type = type;
            inValue.Body.name = name;
            Aim.Portal.ServicesProvider.GwUSService.GetUserDataNodeResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).GetUserDataNode(inValue);
            return retVal.Body.GetUserDataNodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeResponse Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap.SetUserDataNode(Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeRequest request) {
            return base.Channel.SetUserDataNode(request);
        }
        
        public bool SetUserDataNode(string passCode, string type, string name, string newDataNode) {
            Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeRequest inValue = new Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeRequest();
            inValue.Body = new Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeRequestBody();
            inValue.Body.passCode = passCode;
            inValue.Body.type = type;
            inValue.Body.name = name;
            inValue.Body.newDataNode = newDataNode;
            Aim.Portal.ServicesProvider.GwUSService.SetUserDataNodeResponse retVal = ((Aim.Portal.ServicesProvider.GwUSService.UserStateServiceSoap)(this)).SetUserDataNode(inValue);
            return retVal.Body.SetUserDataNodeResult;
        }
    }
}
