//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aim.WorkFlow.WFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WFService.Service_ReceivedDocumentSoap")]
    public interface Service_ReceivedDocumentSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWorkflowTemplatesBindingToEForm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        Aim.WorkFlow.WFService.WorkflowTemplate[] GetWorkflowTemplatesBindingToEForm(System.Guid eFormID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitNewEForm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Guid SubmitNewEForm(Aim.WorkFlow.WFService.ReceivedDocument eFormEntity, System.Guid workflowTemplateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartFlow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Guid StartFlow(System.Guid formInstanceId, string formUrl, string title, string workflowTemplateKey, string userId, string userNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitApprovalResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void SubmitApprovalResult(System.Guid workflowInstanceID, string bookmarkName, Aim.WorkFlow.WFService.ApprovalResult approvalResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTaskListByOwnerAndStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        Aim.WorkFlow.WFService.Task[] GetTaskListByOwnerAndStatus(string owner, Aim.WorkFlow.WFService.WorkItemStatus workItemStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTaskByTaskId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        Aim.WorkFlow.WFService.Task GetTaskByTaskId(string taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEFormEntityByWorkflowInstanceID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        Aim.WorkFlow.WFService.EntityObject GetEFormEntityByWorkflowInstanceID(System.Guid workflowInstanceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEFormMetaDatas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        Aim.WorkFlow.WFService.MetaData_EForm[] GetAllEFormMetaDatas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWorkflowTemplates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        Aim.WorkFlow.WFService.WorkflowTemplate[] GetAllWorkflowTemplates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEFormWorkflowTemplateBinding", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(KeyValuePairOfStringObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WorkflowTemplate[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void UpdateEFormWorkflowTemplateBinding(System.Guid eformTemplateID, string[] boundWorkflowTemplateNames);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WorkflowTemplate : EntityObject {
        
        private string idField;
        
        private string templateNameField;
        
        private string categoryField;
        
        private string descriptionField;
        
        private string versionField;
        
        private string xAMLField;
        
        private string configField;
        
        private string creatorField;
        
        private string lastReviserField;
        
        private System.DateTime createTimeField;
        
        private System.DateTime updateTimeField;
        
        private int statusField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TemplateName {
            get {
                return this.templateNameField;
            }
            set {
                this.templateNameField = value;
                this.RaisePropertyChanged("TemplateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string XAML {
            get {
                return this.xAMLField;
            }
            set {
                this.xAMLField = value;
                this.RaisePropertyChanged("XAML");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Config {
            get {
                return this.configField;
            }
            set {
                this.configField = value;
                this.RaisePropertyChanged("Config");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
                this.RaisePropertyChanged("Creator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LastReviser {
            get {
                return this.lastReviserField;
            }
            set {
                this.lastReviserField = value;
                this.RaisePropertyChanged("LastReviser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
                this.RaisePropertyChanged("UpdateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceivedDocument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MetaData_EForm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Task))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkflowTemplate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SwitchRule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nodeNameField;
        
        private string[] nextActionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NodeName {
            get {
                return this.nodeNameField;
            }
            set {
                this.nodeNameField = value;
                this.RaisePropertyChanged("NodeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] NextActions {
            get {
                return this.nextActionsField;
            }
            set {
                this.nextActionsField = value;
                this.RaisePropertyChanged("NextActions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TimeSpan : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Approver : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private string nameField;
        
        private ApproverValueType valueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ApproverValueType ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
                this.RaisePropertyChanged("ValueType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ApproverValueType {
        
        /// <remarks/>
        ADAccount,
        
        /// <remarks/>
        VirtualRole,
        
        /// <remarks/>
        DepartmentAndRole,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApprovalUnitContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Approver approverField;
        
        private bool canBeSkippedField;
        
        private string skipConditionField;
        
        private ApprovalNodeContext ownerField;
        
        private TimeSpan _DelaySpanField;
        
        private System.Guid taskIDField;
        
        private TimeSpan delaySpanField;
        
        private string bookmarkNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Approver Approver {
            get {
                return this.approverField;
            }
            set {
                this.approverField = value;
                this.RaisePropertyChanged("Approver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool CanBeSkipped {
            get {
                return this.canBeSkippedField;
            }
            set {
                this.canBeSkippedField = value;
                this.RaisePropertyChanged("CanBeSkipped");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SkipCondition {
            get {
                return this.skipConditionField;
            }
            set {
                this.skipConditionField = value;
                this.RaisePropertyChanged("SkipCondition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ApprovalNodeContext Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TimeSpan _DelaySpan {
            get {
                return this._DelaySpanField;
            }
            set {
                this._DelaySpanField = value;
                this.RaisePropertyChanged("_DelaySpan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Guid TaskID {
            get {
                return this.taskIDField;
            }
            set {
                this.taskIDField = value;
                this.RaisePropertyChanged("TaskID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TimeSpan DelaySpan {
            get {
                return this.delaySpanField;
            }
            set {
                this.delaySpanField = value;
                this.RaisePropertyChanged("DelaySpan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BookmarkName {
            get {
                return this.bookmarkNameField;
            }
            set {
                this.bookmarkNameField = value;
                this.RaisePropertyChanged("BookmarkName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApprovalNodeContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private System.Guid idField;
        
        private System.Guid taskGroupIDField;
        
        private string descriptionField;
        
        private ApproverMode modeField;
        
        private ApprovalUnitContext[] approvalUnitContextsField;
        
        private SwitchRule[] switchRulesField;
        
        private bool canBeSkippedField;
        
        private TimeSpan _DelaySpanField;
        
        private ApprovalNodeMatchConditionType matchConditionTypeField;
        
        private SwitchRulePolicy switchRulePolicyField;
        
        private string switchNodesField;
        
        private int currentApproverIndexField;
        
        private TimeSpan delaySpanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid TaskGroupID {
            get {
                return this.taskGroupIDField;
            }
            set {
                this.taskGroupIDField = value;
                this.RaisePropertyChanged("TaskGroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ApproverMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("Mode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public ApprovalUnitContext[] ApprovalUnitContexts {
            get {
                return this.approvalUnitContextsField;
            }
            set {
                this.approvalUnitContextsField = value;
                this.RaisePropertyChanged("ApprovalUnitContexts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public SwitchRule[] SwitchRules {
            get {
                return this.switchRulesField;
            }
            set {
                this.switchRulesField = value;
                this.RaisePropertyChanged("SwitchRules");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool CanBeSkipped {
            get {
                return this.canBeSkippedField;
            }
            set {
                this.canBeSkippedField = value;
                this.RaisePropertyChanged("CanBeSkipped");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public TimeSpan _DelaySpan {
            get {
                return this._DelaySpanField;
            }
            set {
                this._DelaySpanField = value;
                this.RaisePropertyChanged("_DelaySpan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public ApprovalNodeMatchConditionType MatchConditionType {
            get {
                return this.matchConditionTypeField;
            }
            set {
                this.matchConditionTypeField = value;
                this.RaisePropertyChanged("MatchConditionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public SwitchRulePolicy SwitchRulePolicy {
            get {
                return this.switchRulePolicyField;
            }
            set {
                this.switchRulePolicyField = value;
                this.RaisePropertyChanged("SwitchRulePolicy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SwitchNodes {
            get {
                return this.switchNodesField;
            }
            set {
                this.switchNodesField = value;
                this.RaisePropertyChanged("SwitchNodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CurrentApproverIndex {
            get {
                return this.currentApproverIndexField;
            }
            set {
                this.currentApproverIndexField = value;
                this.RaisePropertyChanged("CurrentApproverIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public TimeSpan DelaySpan {
            get {
                return this.delaySpanField;
            }
            set {
                this.delaySpanField = value;
                this.RaisePropertyChanged("DelaySpan");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ApproverMode {
        
        /// <remarks/>
        串行,
        
        /// <remarks/>
        并行,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ApprovalNodeMatchConditionType {
        
        /// <remarks/>
        必须全部同意,
        
        /// <remarks/>
        一个同意即可,
        
        /// <remarks/>
        有一个不同意则退出,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SwitchRulePolicy {
        
        /// <remarks/>
        NextNode,
        
        /// <remarks/>
        Disable,
        
        /// <remarks/>
        UserSpecified,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValuePair_V2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApprovalNodeSkipInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string approvalNodeContextNameField;
        
        private bool canBeSkippedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApprovalNodeContextName {
            get {
                return this.approvalNodeContextNameField;
            }
            set {
                this.approvalNodeContextNameField = value;
                this.RaisePropertyChanged("ApprovalNodeContextName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool CanBeSkipped {
            get {
                return this.canBeSkippedField;
            }
            set {
                this.canBeSkippedField = value;
                this.RaisePropertyChanged("CanBeSkipped");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApprovalResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Task taskField;
        
        private string taskIdField;
        
        private System.DateTime approvalDateTimeField;
        
        private ApprovalOpinion opinionField;
        
        private string commentField;
        
        private ApprovalNodeSkipInfo[] approvalNodeSkipInfoListField;
        
        private KeyValuePair_V2[] extendedPropertiesField;
        
        private ApprovalNodeContext[] specifiedApprovalNodeContextsField;
        
        private KeyValuePair_V2[] switchRulesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Task Task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
                this.RaisePropertyChanged("Task");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TaskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
                this.RaisePropertyChanged("TaskId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ApprovalDateTime {
            get {
                return this.approvalDateTimeField;
            }
            set {
                this.approvalDateTimeField = value;
                this.RaisePropertyChanged("ApprovalDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ApprovalOpinion Opinion {
            get {
                return this.opinionField;
            }
            set {
                this.opinionField = value;
                this.RaisePropertyChanged("Opinion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public ApprovalNodeSkipInfo[] ApprovalNodeSkipInfoList {
            get {
                return this.approvalNodeSkipInfoListField;
            }
            set {
                this.approvalNodeSkipInfoListField = value;
                this.RaisePropertyChanged("ApprovalNodeSkipInfoList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public KeyValuePair_V2[] ExtendedProperties {
            get {
                return this.extendedPropertiesField;
            }
            set {
                this.extendedPropertiesField = value;
                this.RaisePropertyChanged("ExtendedProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public ApprovalNodeContext[] SpecifiedApprovalNodeContexts {
            get {
                return this.specifiedApprovalNodeContextsField;
            }
            set {
                this.specifiedApprovalNodeContextsField = value;
                this.RaisePropertyChanged("SpecifiedApprovalNodeContexts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public KeyValuePair_V2[] SwitchRules {
            get {
                return this.switchRulesField;
            }
            set {
                this.switchRulesField = value;
                this.RaisePropertyChanged("SwitchRules");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Task : EntityObject {
        
        private TaskTaskContext taskContextField;
        
        private string idField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string ownerIdField;
        
        private string ownerField;
        
        private string actionField;
        
        private string workflowInstanceIDField;
        
        private string workFlowNameField;
        
        private string eFormNameField;
        
        private string approvalNodeNameField;
        
        private string groupIDField;
        
        private System.Nullable<int> approvalNodeMatchConditionTypeField;
        
        private string bookmarkNameField;
        
        private System.Nullable<System.DateTime> createdTimeField;
        
        private System.Nullable<System.DateTime> updatedTimeField;
        
        private System.Nullable<System.DateTime> finishTimeField;
        
        private int statusField;
        
        private string contextField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TaskTaskContext TaskContext {
            get {
                return this.taskContextField;
            }
            set {
                this.taskContextField = value;
                this.RaisePropertyChanged("TaskContext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
                this.RaisePropertyChanged("OwnerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string WorkflowInstanceID {
            get {
                return this.workflowInstanceIDField;
            }
            set {
                this.workflowInstanceIDField = value;
                this.RaisePropertyChanged("WorkflowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string WorkFlowName {
            get {
                return this.workFlowNameField;
            }
            set {
                this.workFlowNameField = value;
                this.RaisePropertyChanged("WorkFlowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EFormName {
            get {
                return this.eFormNameField;
            }
            set {
                this.eFormNameField = value;
                this.RaisePropertyChanged("EFormName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ApprovalNodeName {
            get {
                return this.approvalNodeNameField;
            }
            set {
                this.approvalNodeNameField = value;
                this.RaisePropertyChanged("ApprovalNodeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
                this.RaisePropertyChanged("GroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> ApprovalNodeMatchConditionType {
            get {
                return this.approvalNodeMatchConditionTypeField;
            }
            set {
                this.approvalNodeMatchConditionTypeField = value;
                this.RaisePropertyChanged("ApprovalNodeMatchConditionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string BookmarkName {
            get {
                return this.bookmarkNameField;
            }
            set {
                this.bookmarkNameField = value;
                this.RaisePropertyChanged("BookmarkName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> CreatedTime {
            get {
                return this.createdTimeField;
            }
            set {
                this.createdTimeField = value;
                this.RaisePropertyChanged("CreatedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> UpdatedTime {
            get {
                return this.updatedTimeField;
            }
            set {
                this.updatedTimeField = value;
                this.RaisePropertyChanged("UpdatedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> FinishTime {
            get {
                return this.finishTimeField;
            }
            set {
                this.finishTimeField = value;
                this.RaisePropertyChanged("FinishTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class TaskTaskContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ArrayOfTaskContextSwitchRuleSwitchRule[] switchRulesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SwitchRule", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArrayOfTaskContextSwitchRuleSwitchRule[] SwitchRules {
            get {
                return this.switchRulesField;
            }
            set {
                this.switchRulesField = value;
                this.RaisePropertyChanged("SwitchRules");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ArrayOfTaskContextSwitchRuleSwitchRule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ArrayOfTaskContextSwitchRuleNextActionNextAction[] nextActionsField;
        
        private string nodeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NextAction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArrayOfTaskContextSwitchRuleNextActionNextAction[] NextActions {
            get {
                return this.nextActionsField;
            }
            set {
                this.nextActionsField = value;
                this.RaisePropertyChanged("NextActions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NodeName {
            get {
                return this.nodeNameField;
            }
            set {
                this.nodeNameField = value;
                this.RaisePropertyChanged("NodeName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ArrayOfTaskContextSwitchRuleNextActionNextAction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ApprovalOpinion {
        
        /// <remarks/>
        拒绝,
        
        /// <remarks/>
        同意,
        
        /// <remarks/>
        签收确认,
        
        /// <remarks/>
        超时,
        
        /// <remarks/>
        系统取消,
        
        /// <remarks/>
        NA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValuePairOfStringObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceivedDocument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MetaData_EForm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Task))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkflowTemplate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceivedDocument : EntityObject {
        
        private System.Guid idField;
        
        private string senderField;
        
        private System.DateTime receivedDateField;
        
        private string titleField;
        
        private string contentField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReceivedDate {
            get {
                return this.receivedDateField;
            }
            set {
                this.receivedDateField = value;
                this.RaisePropertyChanged("ReceivedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MetaData_EForm : EntityObject {
        
        private System.Guid idField;
        
        private string nameField;
        
        private string versionField;
        
        private string entitySetNameField;
        
        private string keyNameField;
        
        private string remarkField;
        
        private System.Nullable<System.DateTime> createdTimeField;
        
        private System.Nullable<System.DateTime> updatedTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string KeyName {
            get {
                return this.keyNameField;
            }
            set {
                this.keyNameField = value;
                this.RaisePropertyChanged("KeyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> CreatedTime {
            get {
                return this.createdTimeField;
            }
            set {
                this.createdTimeField = value;
                this.RaisePropertyChanged("CreatedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> UpdatedTime {
            get {
                return this.updatedTimeField;
            }
            set {
                this.updatedTimeField = value;
                this.RaisePropertyChanged("UpdatedTime");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum WorkItemStatus {
        
        /// <remarks/>
        Assigned,
        
        /// <remarks/>
        TimeOut,
        
        /// <remarks/>
        Canceled,
        
        /// <remarks/>
        Terminated,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        NA,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service_ReceivedDocumentSoapChannel : Aim.WorkFlow.WFService.Service_ReceivedDocumentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_ReceivedDocumentSoapClient : System.ServiceModel.ClientBase<Aim.WorkFlow.WFService.Service_ReceivedDocumentSoap>, Aim.WorkFlow.WFService.Service_ReceivedDocumentSoap {
        
        public Service_ReceivedDocumentSoapClient() {
        }
        
        public Service_ReceivedDocumentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_ReceivedDocumentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ReceivedDocumentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ReceivedDocumentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Aim.WorkFlow.WFService.WorkflowTemplate[] GetWorkflowTemplatesBindingToEForm(System.Guid eFormID) {
            return base.Channel.GetWorkflowTemplatesBindingToEForm(eFormID);
        }
        
        public System.Guid SubmitNewEForm(Aim.WorkFlow.WFService.ReceivedDocument eFormEntity, System.Guid workflowTemplateID) {
            return base.Channel.SubmitNewEForm(eFormEntity, workflowTemplateID);
        }
        
        public System.Guid StartFlow(System.Guid formInstanceId, string formUrl, string title, string workflowTemplateKey, string userId, string userNames) {
            return base.Channel.StartFlow(formInstanceId, formUrl, title, workflowTemplateKey, userId, userNames);
        }
        
        public void SubmitApprovalResult(System.Guid workflowInstanceID, string bookmarkName, Aim.WorkFlow.WFService.ApprovalResult approvalResult) {
            base.Channel.SubmitApprovalResult(workflowInstanceID, bookmarkName, approvalResult);
        }
        
        public Aim.WorkFlow.WFService.Task[] GetTaskListByOwnerAndStatus(string owner, Aim.WorkFlow.WFService.WorkItemStatus workItemStatus) {
            return base.Channel.GetTaskListByOwnerAndStatus(owner, workItemStatus);
        }
        
        public Aim.WorkFlow.WFService.Task GetTaskByTaskId(string taskId) {
            return base.Channel.GetTaskByTaskId(taskId);
        }
        
        public Aim.WorkFlow.WFService.EntityObject GetEFormEntityByWorkflowInstanceID(System.Guid workflowInstanceID) {
            return base.Channel.GetEFormEntityByWorkflowInstanceID(workflowInstanceID);
        }
        
        public Aim.WorkFlow.WFService.MetaData_EForm[] GetAllEFormMetaDatas() {
            return base.Channel.GetAllEFormMetaDatas();
        }
        
        public Aim.WorkFlow.WFService.WorkflowTemplate[] GetAllWorkflowTemplates() {
            return base.Channel.GetAllWorkflowTemplates();
        }
        
        public void UpdateEFormWorkflowTemplateBinding(System.Guid eformTemplateID, string[] boundWorkflowTemplateNames) {
            base.Channel.UpdateEFormWorkflowTemplateBinding(eformTemplateID, boundWorkflowTemplateNames);
        }
    }
}
